version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/docker/mysql:/var/lib/mysql:delegated
  web:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    volumes:
      - .:/myapp
      - /myapp/node_modules
      - /myapp/vendor
    ports:
      - 8080:3000
    depends_on:
      - db
    stdin_open: true
    tty: true
