default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["RAILS_MAX_THREADS"] %>
  database: <%= ENV["DATABASE_DB_NAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV["DATABASE_PORT"] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["TEST_DATABASE_NAME"] %>
  username: <%= ENV["TEST_DATABASE_USERNAME"] %>
  password: <%= ENV["TEST_DATABASE_PASSWORD"] %>
  host: <%= ENV["TEST_DATABASE_HOST"] %>
  port: <%= ENV["TEST_DATABASE_PORT"] %>


production:
  <<: *default
  pool: 5
  database: app_production
  username: root
  password: password
  url: <%= ENV['JAWSDB_URL'] %>
  master_key: <%= ENV['RAILS_MASTER_KEY'] %>
